## **North-West Rule to find IBFS**

In [41]:
import numpy as np
import sys
fact = [7,9,18]
ware = [5,8,7,14]
weights = np.array([[19,30,50,10],
                    [70,30,40,60],
                    [40,8,70,20]])

In [26]:
def northWestIBFS(fact, ware,weights):
  n = 0
  w = 0
  ibfs = 0
  arr = np.array([[0 for i in range(len(ware))] for i in range(len(fact))])  
  while  n < len(fact) and w < len(ware):
    if fact[n] > ware[w]:
      arr[n][w] = ware[w]
      fact[n] -= ware[w]
      ware[w] = 0
      w += 1
    elif fact[n] < ware[w]:
      arr[n][w] = fact[n]
      ware[w] -= fact[n]
      fact[n] = 0
      n += 1
    else:
      arr[n][w] = fact[n]
      fact[n] = 0
      ware[w] = 0
      n += 1
      w += 1
  for i in range(len(arr)):
    for j in range(len(arr[0])):
      ibfs += arr[i][j] * weights[i][j]
  return arr,ibfs


In [27]:
fact = [7,9,18]
ware = [5,8,7,14]
weights = np.array([[19,30,50,10],
                    [70,30,40,60],
                    [40,8,70,20]])

northWestIBFS(fact, ware,weights)

(array([[ 5,  2,  0,  0],
        [ 0,  6,  3,  0],
        [ 0,  0,  4, 14]]), 1015)

In [28]:
fact = [30,70,50]
ware = [40,30,40,40]
weights = np.array([[19,30,50,10],
                    [70,30,40,60],
                    [40,8,70,20]])

northWestIBFS(fact, ware,weights)

(array([[30,  0,  0,  0],
        [10, 30, 30,  0],
        [ 0,  0, 10, 40]]), 4870)

In [29]:
fact = [10,35,25]
ware = [20,25,25]
weights = np.array([[2,3,1],
                    [5,4,8],
                    [5,6,8]])

northWestIBFS(fact, ware,weights)

(array([[10,  0,  0],
        [10, 25,  0],
        [ 0,  0, 25]]), 370)

In [30]:
fact = [70,
        30,
        50]
ware = [65,42,43]
weights = np.array([[5,7,8],
                    [4,4,6],
                    [6,7,7]])

northWestIBFS(fact, ware,weights)

(array([[65,  5,  0],
        [ 0, 30,  0],
        [ 0,  7, 43]]), 830)

# **Row-Minima method**

In [31]:
def row_MinimaIBFS(fact, ware, weights):
  n = 0
  w = 0
  ibfs = 0
  arr = np.array([[0 for i in range(len(ware))] for i in range(len(fact))]) 
  while  n < len(fact) and w < len(ware):
    if max(ware) > fact[n]:
      w = ware.index(max(ware))
      arr[n][w] = fact[n]
      ware[w] -= fact[n]
      fact[n] = 0
      n += 1
    elif max(ware) < fact[n]:
      w = ware.index(max(ware))
      arr[n][w] = ware[w]
      fact[n] -= ware[w]
      ware[w] = 0
    else:
      w = ware.index(max(ware))
      arr[n][w] = max(ware)
      fact[n] = 0
      ware[w] = 0
      n += 1
      w + 1
  for i in range(len(arr)):
    for j in range(len(arr[0])):
      ibfs += arr[i][j] * weights[i][j]
  return arr,ibfs
      

          

In [32]:

fact = [7,9,18]
ware = [5,8,7,14]
weights = np.array([[19,30,50,10],
                    [70,30,40,60],
                    [40,8,70,20]])

row_MinimaIBFS(fact, ware,weights)

(array([[0, 0, 0, 7],
        [0, 8, 1, 0],
        [5, 0, 6, 7]]), 1110)

In [10]:
fact = [70,
        30,
        50]
ware = [65,42,43]
weights = np.array([[5,7,8],
                    [4,4,6],
                    [6,7,7]])

row_MinimaIBFS(fact, ware,weights)

(array([[65,  0,  5],
        [ 0, 30,  0],
        [ 0, 12, 38]]), 835)

# **Least Cost Method to find IBFS**

In [25]:
weights = np.array([[5,7,8],
                    [5,4,6],
                    [6,2,7]])
np.argwhere(weights == np.min(weights))[0][0]

2

In [60]:
def leastCostIBFS(fact, ware,weights):
  n = 0
  w = 0
  ibfs = 0
  temp_weights = weights.copy()
  arr = np.array([[0 for i in range(len(ware))] for i in range(len(fact))]) 
  while sum(fact) > 0:
    n = np.argwhere(weights == np.min(weights))[0][0]
    w = np.argwhere(weights == np.min(weights))[0][1]
    if fact[n] > ware[w]:
      arr[n][w] = ware[w]
      fact[n] -= ware[w]
      ware[w] = 0
    elif fact[n] < ware[w]:
      arr[n][w] = fact[n]
      ware[w] -= fact[n]
      fact[n] = 0
    else:
      arr[n][w] = fact[n]
      fact[n] = 0
      ware[w] = 0
    weights[n][w] = sys.maxsize
  for i in range(len(arr)):
    for j in range(len(arr[0])):
      ibfs += arr[i][j] * temp_weights[i][j]
  return arr,ibfs

In [61]:
fact = [7,9,18]
ware = [5,8,7,14]
weights = np.array([[19,30,50,10],
                    [70,30,40,60],
                    [40,8,70,20]])

leastCostIBFS(fact, ware,weights)

(array([[0, 0, 0, 7],
        [2, 0, 7, 0],
        [3, 8, 0, 7]]), 814)

In [62]:
fact = [70,
        30,
        50]
ware = [65,42,43]
weights = np.array([[5,7,8],
                    [4,4,6],
                    [6,7,7]])

leastCostIBFS(fact, ware,weights)

(array([[35, 35,  0],
        [30,  0,  0],
        [ 0,  7, 43]]), 890)